server:
  address: localhost
  username: nikola.tesla@mail.com
  password: Zaptec!23
  port: 587
  encryption: explicit # 'disabled' to disable encryption.
                       # 'explicit' uses STARTTLS to upgrade to an encrypted connection (usually on port 587).
                       # 'implicit' forces encryption (usually on port 465).

subject: Zaptec charge report for {{ Metadata.From.strftime('%Y-%m') }}
filename: charger_report_{{ Metadata.From.strftime('%Y_%m') }}

from:
  name: Zaptec Reporter
  address: nikola.tesla@mail.com

to:
  - thomas.edison@mail.com
  - joseph.swan@mail.com

text: |
  Hello,

  See the attached Zaptec charge report covering {{ Metadata.From.strftime('%Y-%m-%d') }} to {{ Metadata.To.strftime('%Y-%m-%d') }}.

  Zap,
  Per Automation

html: >
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <title>Charge report {{ Metadata.From.strftime('%Y-%m-%d') }}</title>
      <style>
        table {
          border-collapse: collapse;
        }
        th, td {
          text-align: left;
          padding: 8px;
          border-bottom: 1px solid #ddd;
        }
        th {
          background-color: #04AA6D;
          color: white;
        }
      </style>
  </head>
  <body>
      <p>
        Hello,<br><br>

        See the attached Zaptec charge report covering {{ Metadata.From.strftime('%Y-%m-%d') }} to {{ Metadata.To.strftime('%Y-%m-%d') }}.<br>

        <table>
          <tbody><tr>
            <th scope="col">Charger</th>
            <th scope="col">Energy (kWh)</th>
          </tr></tbody>
          <tbody>
            {% for item in Usage %}
            <tr>
              <td><b>{{ item.Charger }}</b></td>
              <td>{{ item.Energy|round(2) }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br>

        Zap,<br>
        Per Automation
      </p
  </body>
  </html>
