name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Test
        run: uv run --frozen pytest

      - name: Check
        run: uv run --frozen ruff check --output-format=github .
